Remove janky autostash

diff --git a/hooks/post-merge b/hooks/post-merge
--- a/hooks/post-merge
+++ b/hooks/post-merge
@@ -8,12 +8,12 @@ source ~/.dotfiles/functions/rails_support.sh
 git_system && exit 0
 
 if [[ -f .gitattributes ]] && grep -Fq =lfs .gitattributes; then
-  command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
+  command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path.\n"; exit 2; }
   git lfs post-merge "$@"
 fi
 
-git_file_changed "package.json" && echodo kill_port 3308 && echodo yarn install
-git_file_changed "Gemfile(.lock)?" && echodo bundle install
-git_file_changed "db/(schema.rb|structure.sql)" && rails db:migrate && echodo git stash -- db/schema.rb db/structure.sql
+git_file_changed_after_merge "(package.json|yarn.lock)" && echodo kill_port 3308 && echodo yarn install
+git_file_changed_after_merge "Gemfile(.lock)?" && echodo bundle install
+git_file_changed_after_merge "db/(schema.rb|structure.sql)" && rails db:migrate && echodo git stash -- db/schema.rb db/structure.sql
 
 exit 0
